name: Deploy main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS Deploy
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: git archive --format=zip HEAD --output=deploy.zip

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v19
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: aid-app
          environment_name: Aidapp-env
          version_label: ${{ github.ref_name }}.${{ github.sha }}
          region: us-east-2
          deployment_package: deploy.zip
