name: iOS
on: [pull_request]
jobs:
  publish:
    name: Deploy Preview
    runs-on: ubuntu-latest
    environment: EAS
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: yarn install
        run: yarn install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build iOS App
        run:
          eas build --platform ios --profile preview --non-interactive 2>&1 |
          tee build_output.txt

      - name: Get build link
        run: echo "::set-output name=BUILD_LINK::$(tail -n 1 build_output.txt)"
        id: buildlink

      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg:
            Here's the [iOS Build](${{ steps.buildlink.outputs.BUILD_LINK }}).
